### ISSUE TITLE
Unable to use Reply to Replies

### ISSUE THREAD

**Issue by underwhelmed** [jcutler/Missing-E#1]
When I try to use the Reply to Replies feature on my post list home (http://www.tumblr.com/tumblelog/<username>), I am unable to reply to a reply.  I tried again from my dashboard and I still cannot click on the icon to get a reply post created.

See http://screencast.com/t/4fmzkNv5 for example

Specs:
Mac OS X 10.6
Chrome 9.0.597.102
Extensions Installed;
- 1Password 3.5.8.30873
- AdBlock 2.3.6
- AdBlock Plus for Google Chrome (Beta) 1.0.26
- Missing e 1.0.3f

**Comment by jcutler** [comment]
At the moment, you can only reply to notification boxes (see https://github.com/jcutler/Missing-E/blob/master/chrome/replyReplies/screen.png)

I intend to look into the possibility of replying from loaded notes, but not at the moment.

**Comment by underwhelmed** [comment]
Excellent

**Comment by jcutler** [comment]
This feature is currently in test for the next release. I've got it working in Chrome (but not fully tested) and have not yet ported it to Safari and FF. I'll likely do so this week.

**Comment by jcutler** [comment]
Implemented in version 1.0.54
