### ISSUE TITLE
Hiding posts on the dashboard

### ISSUE THREAD

**Issue by mahmoudhossam** [jcutler/Missing-E#15]
You never know what people post on their blogs, sometimes you can find something that is disturbing, inappropriate, or simply unwanted.

I'd like to be able to hide posts from the dashboard, something like a minimize button on the post that shows a slim bar instead of the post, in case I wanted to show the post again.

And, if possible, be able to hide a certain user from appearing on the dashboard, sometimes I don't want to see a specific person's posts, but can't unfollow them for one reason or the other, that'd be nice as well, although not completely necessary.

**Comment by parkr** [comment]
You mean have the post sort of fold up into the info bar (where the timestamp and action buttons are)?
Why wouldn't you be able to unfollow them? I'll look into both of these.

**Comment by jcutler** [comment]
I'm not sure that's what he meant. He wants to globally hide all posts by a user. Also, I'm guessing that the feature would not be useful unless the hiding of the post persisted across reloads of the dash.

Manually hiding a single post that has already been loaded doesn't really add much value, I think.

Also, thanks for the German translation fixes. Would you mind looking through all the German translations and correcting? Just do a grep for "de:" and it should find all the files with German text.

**Comment by parkr** [comment]
I thought it was two-fold. I already completed the first one but it was quick (like 15 lines of code) so no big deal.
Sure, I'll look through all the German translation fixes. Only fixed one or two that i found and only in Chrome (for testing - it was bugging me)

**Comment by mahmoudhossam** [comment]
I'm sorry, I totally forgot I posted this, I meant hiding all posts by a user, as jcutler said, also hiding a single post might be helpful, since some posts might be disturbing, offensive for a user, or just simply unwanted

**Comment by jcutler** [comment]
It's a good idea in principle, but the execution is not straightforward.

I don't agree with the need to hide all posts by a user. If you wanted that, why not unfollow or ignore? I'm not sure what the value-add is for that. Safe Dash can protect you from offensive imagery. Maybe you can clarify what the need is?

As for hiding a single post, it can be done as parkr established, but in order for it to persist (the next time you load the dash, or later the post is loaded with the endless dash) there would have to be data stored in local storage. When would we clear that data? Also, the more posts that get added to that list without being cleared out, the longer the dash would take to process (Missing e would slow down).

Also, for the purposes of hiding stuff on the dash, I'd suggest you take a look at [Tumblr Saviour](https://chrome.google.com/webstore/detail/oefddkjnflmjbclpnnoegglmmdfkidip)

**Comment by mahmoudhossam** [comment]
Sometimes you just can't afford to unfollow :D

I guess hiding single posts might be more plausible, you can save the data for a week, I guess that's enough time for it to get  really old that nobody would ever see it on the dashboard.

Thanks for the link :)

**Comment by parkr** [comment]
@mhh91 I'm not convinced this will be implemented.
