### ISSUE TITLE
Update JQuery to v1.6.1

### ISSUE THREAD

**Issue by parkr** [jcutler/Missing-E#17]
Currently using v1.5.

**Comment by jcutler** [comment]
I'll try testing that it works before release 1.2.1 (which should be the next release). Firefox may be the only issue

**Comment by parkr** [comment]
Ok great - I noticed you updated when I loaded the pack into Chrome. I'm working on it now. Know of any problems with compatibility?

**Comment by jcutler** [comment]
The only real concerns are pretty much everything on Firefox, and across all of them the facebox (for magnifier, follow checker, unfollower) and the toggle switches on the options page.
