### ISSUE TITLE
Incorrectly create column on Options page

### ISSUE THREAD

**Issue by parkr** [jcutler/Missing-E#20]
Screenshot: http://cl.ly/2F35362t322S0g252P2a

**Comment by jcutler** [comment]
What browser/OS? I haven't seen this. Does this happen every time?
It doesn't make any sense, all the styles are inlined, the fonts shouldn't even be that colour.

**Comment by parkr** [comment]
Chrome/Mac, just like before.
But I figured it out - it was another plugin (Tumblr Sidebar).
Sorry!
