### ISSUE TITLE
Bookmark rename lets you use non-alpha/numeric/space characters

### ISSUE THREAD

**Issue by jackholt** [jcutler/Missing-E#4]
I just renamed a bookmark to "Sad Bunny :( ".

(That final character, if it doesn't come through, is the Apple symbol, code point U+F8FF)

I don't know if this is a bug or not. It may be as designed.

**Comment by jcutler** [comment]
That's a feature :)
Basically, the issue that was there that required me to force it to use only alphanumerics is gone. It will convert commas and semicolons to periods though.

If you see any message or warning that says it has to be alphanumeric, let me know so I can fix it!
