### ISSUE TITLE
Timestamp is sometimes wrong

### ISSUE THREAD

**Issue by jackholt** [jcutler/Missing-E#5]
For example, this post's timestamp is off by 4 hours:

http://mountainstandardtime.tumblr.com/post/3695147099/9-15-pm-mar-06-sun-mst

**Comment by jcutler** [comment]
I've seen this problem, myself. It isn't a problem with my code, but the Tumblr API.

Take a look at an API read for that post:
http://mountainstandardtime.tumblr.com/api/read/json?id=3695147099

Especially pay attention to this field:
"date-gmt":"2011-03-07 08:15:01 GMT"

Tumblr is clearly reporting an incorrect date, but there's not much I can do about that.
