### ISSUE TITLE
Feature request - default new posts to "add to queue"

### ISSUE THREAD

**Issue by jackholt** [jcutler/Missing-E#6]
It would be wonderful to have a feature -- off by default, of course -- which would make the new post pages default to "Add to Queue". 

It sounds like you are in feature freeze before release, but I wanted to put this out there for the future. I'd use it a lot.

**Comment by jcutler** [comment]
This is in the works. It's already ready on all platforms for the next release, I'm just putting finishing touches on it and waiting for another feature or two to be done prior to releasing it.

**Comment by jackholt** [comment]
I saw a preview on tumblr. It looks great!

On Mon, Mar 21, 2011 at 6:27 AM, jcutler
reply@reply.github.com
wrote:

**Comment by jcutler** [comment]
Implemented in version 1.0.54

**Comment by jackholt** [comment]
Sweeeeeeeeet! I think I'll go queue something. ;^)

On Mon, Mar 21, 2011 at 1:25 PM, jcutler
reply@reply.github.com
wrote:
